### ISSUE TITLE
Nordpool stopped working after update to 0.7

### ISSUE THREAD

**Issue by vikreh** [custom-components/nordpool#196]
Checking configuration.yaml results in a not valid configuration message as follows:

Platform error sensor.nordpool - cannot import name 'pass_context' from 'jinja2' (/srv/homeassistant/lib/python3.8/site-packages/jinja2/__init__.py)

How can this be resolved?
Help appreciated -BR

**Comment by vikreh** [comment]
Issue resolved by updating to latest version of Home Assistant
