### PR TITLE
Fix #131

### LINKED ISSUE #131: Integration not working in 2022.4.0b0
## Version of the custom_component

0.0.4

## Homeassistant version
2022.4.0b0

## Configuration

```yaml
sensor:
  - platform: nordpool
```

## Describe the bug
The integration fails to load in 2022.4.0b0. 
The config flow gives the following error:
```
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.
```
See below for error in log which is present both when starting the config flow and when trying to load the sensor in yaml.

## Debug log

```text
Platform error sensor.nordpool - cannot import name 'contextfunction' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)
```

### PR DESCRIPTION
**Pull request by Hellowlol**
https://github.com/custom-components/nordpool/issues/131

### CODE REVIEW

**Comment by Inrego** [comment]
Now that 2022.4 is officially out, I think it's time to make a new release with this patch.
