### ISSUE TITLE
Something broke with update to Home Assistant Core 2022.5

### ISSUE THREAD

**Issue by MadHouseDK** [custom-components/nordpool#146]
Got this error after updating homeassistant to 2022.5 and reboot:
--------------------------------------------------------------------------------------------------------------------------------
"Invalid config
The following integrations and platforms could not be set up:

[nordpool](https://github.com/custom-components/nordpool/) ([Show logs]
Please check your config and [logs]."

--------------------------------------------------------------------------------------------------------------------------------

Log:
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/nordpool/__init__.py", line 17, in <module>
    from .events import async_track_time_change_in_tz
  File "/config/custom_components/nordpool/events.py", line 4, in <module>
    from homeassistant.const import ATTR_NOW, EVENT_TIME_CHANGED
ImportError: cannot import name 'EVENT_TIME_CHANGED' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2022-05-04 21:42:56 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration nordpool: Unable to import component: cannot import name 'EVENT_TIME_CHANGED' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by Hemma4** [comment]
Samme for me

**Comment by Wizard6969** [comment]
Same here too

**Comment by aherbjornsen** [comment]
This issue is a duplicate of: https://github.com/custom-components/nordpool/issues/143

**Comment by zipperten** [comment]
Im in line!

**Comment by MadHouseDK** [comment]
Sorry for duplicate.   :o/

**Comment by riksarchen** [comment]
Same here:
This error originated from a custom integration.

Logger: homeassistant.config
Source: custom_components/nordpool/events.py:4 
Integration: nordpool (documentation, issues) 
First occurred: 23:11:53 (2 occurrences) 
Last logged: 23:11:53

Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/nordpool/__init__.py", line 17, in <module>
    from .events import async_track_time_change_in_tz
  File "/config/custom_components/nordpool/events.py", line 4, in <module>
    from homeassistant.const import ATTR_NOW, EVENT_TIME_CHANGED
ImportError: cannot import name 'EVENT_TIME_CHANGED' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by Hellowlol** [comment]
The latest update should fix this issue. Please confirm.

**Comment by kingzize** [comment]
> The latest update should fix this issue. Please confirm.

Upgraded to 0.0.6, when trying to restart HA the following error occurs:

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:668
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 23:23:38 (1 occurrences)
Last logged: 23:23:38

The system cannot restart because the configuration is not valid: Component error: nordpool - Exception importing custom_components.nordpool Platform error sensor.nordpool - Exception importing custom_components.nordpool.sensor

**Comment by Hellowlol** [comment]
Post the trace back. What python version and install type are you using?

**Comment by kingzize** [comment]
Installed via HACS. 
Forced reboot of the host. 

Following error:

Logger: homeassistant.loader
Source: custom_components/nordpool/events.py:31
Integration: nordpool ([documentation](https://github.com/custom-components/nordpool/), [issues](https://github.com/custom-components/nordpool/issues))
First occurred: 23:37:31 (2 occurrences)
Last logged: 23:37:31

Unexpected exception importing component custom_components.nordpool
Unexpected exception importing platform custom_components.nordpool.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 584, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/nordpool/__init__.py", line 17, in <module>
    from .events import async_track_time_change_in_tz
  File "/config/custom_components/nordpool/events.py", line 31, in <module>
    action: Callable[[datetime], Awaitable[None] | None],
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'

**Comment by el97** [comment]
This is happening to me as well.

**Comment by jml002021** [comment]
Same here, not working

**Comment by jml002021** [comment]
> Post the trace back. What python version and install type are you using?

Is it working with you?

**Comment by jml002021** [comment]
Unexpected exception importing component custom_components.nordpool
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 584, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/nordpool/__init__.py", line 17, in <module>
    from .events import async_track_time_change_in_tz
  File "/config/custom_components/nordpool/events.py", line 31, in <module>
    action: Callable[[datetime], Awaitable[None] | None],
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'

**Comment by Hellowlol** [comment]
> > Post the trace back. What python version and install type are you using?
> 
> Is it working with you?

Yeah, it worked in my dev container but not my ha install the only change is that the dev container uses a newer python version.

**Comment by GunnarBjoru** [comment]
It works now with version 0.0.7. Thank you

**Comment by jml002021** [comment]
Thanks for fast repair "version 0.0.7" working fine.
