### ISSUE TITLE
"Unable to prepare setup for platform nordpool.sensor after updating to 0.15.

### ISSUE THREAD

**Issue by niklaswik86** [custom-components/nordpool#426]
I just tried updating to 0.15 and now I get this error on startup (had 0.14 until now, which did not cause any errors, just didn't get any data). 
```

Logger

: homeassistant.setup
Source: setup.py:366
First occurred: 09:41:35 (1 occurrences)
Last logged: 09:41:35

Unable to prepare setup for platform nordpool.sensor: Unable to set up component.

```
Also this: 
```

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/nordpool/__init__.py:179
Integration: Nord Pool (documentation, issues)
First occurred: 09:41:35 (1 occurrences)
Last logged: 09:41:35

Error during setup of component nordpool
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/nordpool/__init__.py", line 197, in async_setup
    return await _dry_setup(hass, config)
  File "/config/custom_components/nordpool/__init__.py", line 179, in _dry_setup
    tz=await dt_utils.async_get_time_zone("Europe/Stockholm"),
AttributeError: module 'homeassistant.util.dt' has no attribute 'async_get_time_zone'

```
I have tried removing nordpool and my old sensor.nordpool, and reinstalling it from HACS.

**Comment by chrkeijzer** [comment]
I have the same problem:

2024-10-23 09:59:48.207 DEBUG (MainThread) [custom_components.nordpool] Added nordpool to hass.data
2024-10-23 09:59:48.208 ERROR (MainThread) [homeassistant.setup] Error during setup of component nordpool
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/homeassistant/setup.py", line 390, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/nordpool/__init__.py", line 197, in async_setup
    return await _dry_setup(hass, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/nordpool/__init__.py", line 179, in _dry_setup
    tz=await dt_utils.async_get_time_zone("Europe/Stockholm"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Hellowlol** [comment]
Update your Home Assistant install. Seems you are running a old version. Remember to take backup of ha first

**Comment by PeteSapai** [comment]
I might have the same problem, my log is exactly the same.

As of a couple of days ago the nordpool.sensor stopped working and apexchards showed an empty graph. I noticed there was an update for the Nordpool integration (I was running either 0.0.13 or 14, I updated to .15), which didn’t solve it. I also updated HACS (from 1.31.x to 1.34), also to no avail.

When I add a nordpool integration (Region: NL) It says “Succes Created configuration for Nordpool”, but also “The integration could not be loaded, try to restart HA”. (An HA restart doesn’t solve this; in Settings - devices - integrations nordpool still says “not loaded” and clicking it then says “No devices or entities”.)

@Hellowlol: you suggest updating HA. Which version would be too old for nordpool 0.0.15? I’m running Home Assistant 2023.9.2...

**Comment by niklaswik86** [comment]
> Update your Home Assistant install. Seems you are running a old version. Remember to take backup of ha first

Thanks! Updated HA and updated HACS as well, now all is fine. Sometimes the solution is so simple.

**Comment by PeteSapai** [comment]
> > Update your Home Assistant install. Seems you are running a old version. Remember to take backup of ha first
> 
> Thanks! Updated HA and updated HACS as well, now all is fine. Sometimes the solution is so simple.

Pleeeaaaase, people, if you post stuff like this, go into a little bit more detail. Pretty please! What version of HA and HACS were you running and did you update to the latest ones?

**Comment by Hellowlol** [comment]
@PeteSapai I could say pretty please use the issue template. Nordpool works with the latest public version

**Comment by niklaswik86** [comment]
> > > Update your Home Assistant install. Seems you are running a old version. Remember to take backup of ha first
> > 
> > 
> > Thanks! Updated HA and updated HACS as well, now all is fine. Sometimes the solution is so simple.
> 
> Pleeeaaaase, people, if you post stuff like this, go into a little bit more detail. Pretty please! What version of HA and HACS were you running and did you update to the latest ones?

Sorry.
I had forgotten to update for quite a while, so I was running 2023.4.6 and HACS 1.33.

**Comment by PeteSapai** [comment]
Hey, thanks! So 1 year and 4 months is too old already? Then 1y1m might be, too. Crap, I'm gonna have to update, I really hope it goes well and I don't have to setup everything again. Oh well, we'll see...
