### ISSUE TITLE
Integration not working in 2022.4.0b0

### ISSUE THREAD

**Issue by Skeletorjus** [custom-components/nordpool#131]
## Version of the custom_component

0.0.4

## Homeassistant version
2022.4.0b0

## Configuration

```yaml
sensor:
  - platform: nordpool
```

## Describe the bug
The integration fails to load in 2022.4.0b0. 
The config flow gives the following error:
```
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.
```
See below for error in log which is present both when starting the config flow and when trying to load the sensor in yaml.

## Debug log

```text
Platform error sensor.nordpool - cannot import name 'contextfunction' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)
```

**Comment by Skeletorjus** [comment]
Wow, that was fast! Can confirm that the fix is working 👍
